//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileStoreMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string MCompany { get; set; }
        public string MModel { get; set; }
        public Nullable<int> MPrice { get; set; }
        public string MSpecification { get; set; }
        public Nullable<int> MQty { get; set; }
        public string MPhoto { get; set; }
    }
}
